module.exports = {
  hypothetical: [
    "If you could swap lives with any fictional character for a week, who would it be and what would you do first?",
    "If we had to move to any country tomorrow with zero preparation, where would you pick and why?",
    "If you could have dinner with any person from history, who would it be and what would you ask them?",
    "If you woke up tomorrow as the president of any country, which one and what is your first decree?",
    "If a genie granted you three wishes but one had to be completely ridiculous, what would your wishes be?",
    "If you could instantly become a world expert in one completely useless skill, what would you pick?",
    "If we were characters in a movie, what genre would it be and who would play us?",
    "If you could eat only one cuisine for the rest of your life, what would it be?",
    "If you had a time machine but could only use it once, where and when would you go?",
    "If you could live inside any TV show for a month, which one would you choose?",
    "If you could have any animal as a perfectly trained pet, what would you choose?",
    "If you suddenly had the ability to read minds, would you use it? What would you do first?",
    "If you could wake up tomorrow fluent in any three languages, which would you pick?",
    "If you were given a million dollars but had to spend it all in 24 hours, what would you buy?",
    "If you could relive one year of your life with everything you know now, which year?",
    "If you had to survive a zombie apocalypse, what three items would you grab first?",
    "If aliens landed and asked you to explain humanity in one sentence, what would you say?",
    "If you could create a holiday that everyone in the world had to celebrate, what would it be?",
    "If you could master any musical instrument overnight, which would you choose and what would you play first?",
    "If you were invisible for a day, what would you do?",
    "If you could switch two historical events so they happened in each other's time period, which two?",
    "If you could design your dream job from scratch — no rules, unlimited budget — what would it look like?",
    "If you were a superhero, what would your power be, your name, and your fatal weakness?",
    "If you could bring one extinct species back to life, which one and why?",
    "If we got teleported to a deserted island right now, what is the first thing you would do?",
    "If you had to teach a college class on any subject, what would it be?",
    "If you could make one rule that everyone on Earth had to follow, what would it be?",
    "If you could experience one day in any era of history, which day would you pick?",
    "If you discovered you had a secret twin, what do you think they would be like?",
    "If you could only watch one movie on repeat for the rest of your life, which one?"
  ],

  childhood: [
    "What is the most vivid memory you have from before age 10?",
    "What game or activity were you absolutely obsessed with as a kid?",
    "Tell me about your best friend when you were little. Are you still in touch?",
    "What was the first thing you ever saved up your own money to buy?",
    "Describe the house you grew up in. Which room was your favorite?",
    "What is the most trouble you ever got into as a kid?",
    "What did you want to be when you grew up? When did that dream change?",
    "What was your favorite family tradition growing up?",
    "What was the first movie or show that absolutely blew your mind as a child?",
    "Tell me about a teacher who made a real impact on you.",
    "What was your favorite hiding spot when you were young?",
    "What is a food you loved as a kid but cannot stand now, or vice versa?",
    "What was your most embarrassing moment in school?",
    "Did you have a childhood crush? Tell me the story.",
    "What was the bravest thing you did as a kid?",
    "Tell me about a birthday you remember really well. What made it special?",
    "What was your favorite thing to do during summer break?",
    "Did you have a stuffed animal or toy you were inseparable from? What was its name?",
    "What was your favorite bedtime story or the one you asked for over and over?",
    "Tell me about a family road trip or vacation from when you were young.",
    "What is a lesson your parents taught you that you still carry with you?",
    "What was your first pet? Tell me everything about them.",
    "What was the first concert, play, or big event you ever attended?",
    "Tell me about a time you stood up for someone when you were young.",
    "What was the weirdest phase you went through as a teenager?",
    "What is a smell that instantly takes you back to your childhood?",
    "Tell me about the neighborhood you grew up in. What made it special?",
    "What was the first album or song you were completely obsessed with?",
    "What was your favorite subject in school and why?",
    "Tell me about a moment from your childhood that shaped who you are today."
  ],

  spicy: [
    "What was your very first impression of me when we met? Be honest.",
    "What is something I do that drives you crazy in the best way?",
    "Describe a moment between us that still gives you butterflies.",
    "What is a date we have not been on yet that you have been secretly wanting?",
    "If you could relive one intimate moment between us, which one would you choose?",
    "What is something you find attractive about me that you have never told me?",
    "What song makes you think of me and why?",
    "What was going through your mind right before our first kiss?",
    "What outfit or look of mine makes it hardest for you to concentrate?",
    "What is a fantasy date night you have imagined but never brought up?",
    "Where is the most adventurous place you would want us to be intimate?",
    "What is the most attractive thing I have ever said to you?",
    "If we had a whole weekend alone with no responsibilities, how would you want to spend it?",
    "What is a secret turn-on you have not shared with me yet?",
    "Describe the perfect way for me to seduce you.",
    "What physical feature of mine are you most drawn to and why?",
    "What is something new you want us to try together in the bedroom?",
    "What is the most memorable compliment I have ever given you?",
    "If you could set the scene for the perfect romantic evening, what would it look like?",
    "Tell me about a time you wanted to kiss me but held back. What stopped you?",
    "What do I do in everyday life that you find unexpectedly attractive?",
    "What is a word or phrase I say that sends shivers down your spine?",
    "If you could choreograph our perfect slow dance, what song would play?",
    "What is the boldest thing you wish I would do more often?",
    "Describe your favorite way to be touched without using the word 'touch'.",
    "What is a romantic movie scene you wish we could recreate?",
    "What was the moment you knew the physical chemistry between us was real?",
    "If you could read my mind for just one moment, which moment would you choose?",
    "What is the most romantic text or message I have ever sent you?",
    "Tell me something you want to whisper to me but have been too shy to say."
  ],

  dreams: [
    "What is one thing on your bucket list you have not told anyone about?",
    "If money were no object, what would our life look like in 10 years?",
    "What skill or hobby do you wish you could master overnight?",
    "If we could design our dream home together, what is the one non-negotiable feature?",
    "What adventure do you want us to have together in the next year?",
    "If you could wake up tomorrow having gained one ability, what would it be?",
    "Where do you see yourself at 80, and what do you hope you will have done by then?",
    "What is something you have always wanted to learn but keep putting off?",
    "If you could start a business with no risk of failure, what would it be?",
    "What is a place you have never been but feel like you are meant to visit?",
    "If you could change one thing about how you spend your days, what would it be?",
    "What is a dream you had as a child that you still quietly hold onto?",
    "If we won the lottery tomorrow, what is the very first thing you would want to do?",
    "What kind of legacy do you want to leave behind?",
    "If you could spend a year doing absolutely anything, what would your year look like?",
    "What is a fear you want to conquer in the next five years?",
    "If we could take a sabbatical together, where would we go and what would we do?",
    "What does your ideal regular Tuesday look like in five years?",
    "What is something you want to build, create, or make with your own hands?",
    "If you could guarantee one thing about our future, what would it be?",
    "What is a cause or mission you feel passionate about and want to do more for?",
    "If you could live in any city in the world for a year, which one?",
    "What do you hope people say about you when you are not in the room?",
    "What is something you want us to accomplish together as a team?",
    "If you could write a book about anything, what would it be about?",
    "What does retirement look like in your imagination?",
    "What is a tradition you want to start in our life together?",
    "If you had a year off and unlimited funds for education, what would you study?",
    "What is the wildest dream you have that you think might actually be possible?",
    "Where do you want to be on your next birthday, and who do you want there?"
  ],

  love: [
    "What is the smallest thing I do that makes you feel most loved?",
    "When did you first realize this was something more than a crush?",
    "What is one way I have changed you for the better?",
    "What is one thing I could do more often that would make your day?",
    "Describe a moment where you felt completely understood by me.",
    "What is the best compliment you have ever received from anyone?",
    "How do you know when you are loved? What does it feel like?",
    "What is something about our relationship that you are really proud of?",
    "What is a small act of love someone did for you that you never forgot?",
    "When do you feel most connected to me?",
    "What is something I do that you want to make sure I never stop doing?",
    "How did your parents show love to each other? How did that shape you?",
    "What does feeling safe in a relationship mean to you?",
    "What is your favorite memory of us that you replay in your head?",
    "What is something about me that you had to grow to appreciate?",
    "How do you most like to receive an apology?",
    "What is a moment when you felt incredibly grateful for us?",
    "What is your love language and when did you figure it out?",
    "What is something I have forgiven you for that meant a lot?",
    "How do you like to be comforted when you are having a bad day?",
    "What is a relationship lesson you learned the hard way?",
    "What is a quality in me that you hope to see in our future together?",
    "When was a time I made you feel like the most important person in the room?",
    "What does home feel like to you? Is it a place, a person, or a feeling?",
    "What is something you admire about how we handle disagreements?",
    "What is a vulnerability you have shared with me that brought us closer?",
    "What is a promise you want us to make to each other?",
    "What do you think is the secret to keeping love alive over the years?",
    "What is the kindest thing a stranger has ever done for you?",
    "If you could bottle one feeling from our relationship, which moment would it be from?"
  ]
};
