module.exports = {
  hypothetical: [
    "If you could swap lives with any fictional character for a week, who would it be and what would you do first?",
    "If we had to move to any country tomorrow with zero preparation, where would you pick and why?",
    "If you could have dinner with any person from history, who would it be and what would you ask them?",
    "If you woke up tomorrow as the president of any country, which one and what is your first decree?",
    "If a genie granted you three wishes but one had to be completely ridiculous, what would your wishes be?",
    "If you could instantly become a world expert in one completely useless skill, what would you pick?",
    "If we were characters in a movie, what genre would it be and who would play us?",
    "If you could eat only one cuisine for the rest of your life, what would it be?",
    "If you had a time machine but could only use it once, where and when would you go?",
    "If you could live inside any TV show for a month, which one would you choose?",
    "If you could have any animal as a perfectly trained pet, what would you choose?",
    "If you suddenly had the ability to read minds, would you use it? What would you do first?",
    "If you could wake up tomorrow fluent in any three languages, which would you pick?",
    "If you were given a million dollars but had to spend it all in 24 hours, what would you buy?",
    "If you could relive one year of your life with everything you know now, which year?",
    "If you had to survive a zombie apocalypse, what three items would you grab first?",
    "If aliens landed and asked you to explain humanity in one sentence, what would you say?",
    "If you could create a holiday that everyone in the world had to celebrate, what would it be?",
    "If you could master any musical instrument overnight, which would you choose and what would you play first?",
    "If you were invisible for a day, what would you do?",
    "If you could switch two historical events so they happened in each other's time period, which two?",
    "If you could design your dream job from scratch — no rules, unlimited budget — what would it look like?",
    "If you were a superhero, what would your power be, your name, and your fatal weakness?",
    "If you could bring one extinct species back to life, which one and why?",
    "If we got teleported to a deserted island right now, what is the first thing you would do?",
    "If you had to teach a college class on any subject, what would it be?",
    "If you could make one rule that everyone on Earth had to follow, what would it be?",
    "If you could experience one day in any era of history, which day would you pick?",
    "If you discovered you had a secret twin, what do you think they would be like?",
    "If you could only watch one movie on repeat for the rest of your life, which one?",
    "If you could have dinner with any three people from history, who would you invite and what would you cook?",
    "If we could teleport anywhere in the world right now for one hour, where would we go?",
    "If you could relive one day of your life on repeat forever, which day would you pick?",
    "If you woke up tomorrow with one new superpower, what would it be and how would you use it first?",
    "If our relationship was turned into a Broadway musical, what would the opening number be called?",
    "If you could speak to any animal for a day, which species and what would you ask?",
    "If you could permanently change one law of physics, which one would you bend and why?",
    "If we were stranded on a desert island with only three items each, what would you bring?",
    "If you could time travel to any decade just to live in it for a month, when would you go?",
    "If you found a genie but could only wish for things smaller than a breadbox, what would you wish for?",
    "If you could make one food completely calorie-free forever, which would you choose?",
    "If you had to win a reality competition show, which one would you absolutely dominate?",
    "If our love story became a bedtime fairytale, how would it begin?",
    "If you could bring back one extinct creature as a pet, which would you pick?",
    "If you could invent a new sense beyond the five we have, what would it detect?",
    "If you could have a conversation with your future self, what age would you want them to be?",
    "If you had to run for mayor of our town tomorrow, what would your campaign slogan be?",
    "If we opened a shop together out of nowhere, what would we sell and what would it be called?",
    "If you could master any musical instrument overnight, which one would you play first and where?",
    "If you were given a magic paintbrush that made anything real, what would you paint first?",
    "If you could witness any event in history as an invisible observer, which would you choose?",
    "If you could rename yourself completely, what name would you pick and why?",
    "If you could turn any fictional technology into reality, what would you bring to life?",
    "If we woke up as each other for a day, what is the first thing you would do in my body?",
    "If you were cursed to only speak in movie quotes for a week, which film would you choose?",
    "If you could design a theme park based on your personality, what rides would it have?",
    "If you could erase one invention from history, which would you vanish and why?",
    "If you could have any mythical creature as a best friend, which one and what would you do together?",
    "If you had to replace one of your senses with echolocation, which would you give up?",
    "If you could write a letter to your teenage self, what would the first sentence be?",
    "If we had to survive a zombie apocalypse, what is your unexpected weapon of choice?",
    "If you could make one of your dreams last forever, which dream would you stay inside?",
    "If you discovered a hidden door in our home, where would you want it to lead?",
    "If you could be any age forever, which age would you freeze at and why?",
    "If you could start a new religion with one silly commandment, what would the rule be?",
    "If you could turn one hobby into a wildly successful career tomorrow, which would it be?",
    "If you could live inside any painting for a day, which artwork would you step into?",
    "If you had to compete in the Olympics in a made-up sport, what would the sport be?",
    "If you could have one celebrity narrate your daily life, who would you pick?",
    "If you could combine two animals into one new creature, what would you create?",
    "If you had to teach a college class on something unusual, what would the syllabus include?",
    "If you could switch bodies with any historical figure for one afternoon, who would it be?",
    "If the two of us formed a crime-fighting duo, what would our team name be?",
    "If you could give every child in the world one gift, what would you choose?",
    "If your life had a laugh track, when would it play the loudest?",
    "If you could add one room to our dream house that serves no purpose, what would it be?",
    "If you could make any inanimate object sentient, what would you bring to life?",
    "If you had to disappear for a year with no contact, where would you hide?",
    "If you could summon any fictional mentor to give you advice, who would you call?",
    "If you had unlimited money but only 24 hours to spend it, what is your first purchase?",
    "If you could reboot any old TV show starring us, what would it be called?",
    "If you had to live in any video game world forever, which would you pick?",
    "If you could plant a garden that grew anything at all, what would sprout?",
    "If we accidentally started a cult, what would its core belief be?",
    "If you could whisper one secret into history's ear, what would you change?",
    "If you could sleep for a full year and wake up in any year, when would you return?",
    "If you could instantly be fluent in any dead language, which would you choose?",
    "If your spirit animal showed up at the door, what do you think it would look like?",
    "If you could throw the most absurd themed party, what would be the dress code?",
    "If you had to pick one fictional villain to befriend, who would you chat with over coffee?",
    "If your life had a mascot, what would it be and what would it wear?",
    "If you could take one trip into outer space, where in the solar system would you visit?",
    "If we accidentally became pirates, what would our ship be called?",
    "If you could bottle one feeling and sell it, which emotion would you market?",
    "If you had to give up one color forever, which would you banish from your life?",
    "If you could write one law everyone had to follow on Sundays, what would it be?",
    "If your childhood imaginary friend came back, what would they look like now?",
    "If you could swap your morning routine with any historical figure, whose would you steal?",
    "If you could build a treehouse with no limits, what would be inside it?",
    "If you had to explain the internet to someone from the 1700s, how would you start?",
    "If you could be haunted by a friendly ghost, who from history would you want?",
    "If you could train under any wise old mentor from fiction, who would teach you?",
    "If you found a message in a bottle from the future, what would you hope it said?",
    "If you could star in any film ever made, which role would you steal?",
    "If the moon suddenly turned a new color, what color should it be?",
    "If you could send one song into space to represent humanity, which would you pick?",
    "If we became inventors overnight, what would our first patent be for?",
    "If you had to replace coffee with a new morning ritual, what would it be?",
    "If you could be reincarnated as any object, what would you come back as?",
    "If you could steal one fashion trend from any era, what would you rock today?",
    "If you had to create a new national anthem in five words, what would it say?",
    "If our future kid came back from the future to warn us, what would they say?",
    "If you could talk to plants and they talked back, what would you ask your favorite one?",
    "If you could invent a new flavor of ice cream, what is in it and what is it called?",
    "If you could host a talk show with any three guests, living or dead, who would be on?",
    "If you had to survive entirely off one meal for life, what would it be?",
    "If you could leave a tiny message for aliens to find someday, what would it say?",
    "If we were royalty in a made-up kingdom, what would our kingdom be famous for?",
    "If you could have one mythical skill, like Midas touch, what would it be?",
    "If you could step inside a book and change its ending, which would you rewrite?",
    "If you had to choose a theme song that played whenever you walked into a room, what is it?",
    "If you could send your younger self one object from today, what would it be?",
    "If you could build a museum dedicated to anything, what would it celebrate?",
    "If you could swap places with a stranger for a week, who would you pick off the street?",
    "If you could replace gravity with something else, what should hold us down?",
    "If the two of us wrote a cookbook together, what would our strangest recipe be?",
    "If you could create a constellation in the night sky, what shape would it be?",
    "If you could adopt any fictional pet, which one would you bring home?",
    "If you were given a magic mirror that only told truths, what would you ask it first?",
    "If you could invent a new dance craze, what moves would it involve?",
    "If you had to give a TED Talk tomorrow on any topic, what would you present?",
    "If you could bring any cartoon to life in our living room, which one would it be?",
    "If you woke up tomorrow as a Pixar character, which movie would you belong in?",
    "If you could rename the days of the week, what would they become?",
    "If you could turn one chore into an Olympic sport, which would you compete in?",
    "If you had a button that summoned any snack instantly, what would you program it with?",
    "If you could leave a time capsule for our grandkids, what would you put inside?",
    "If you could add a thirteenth month to the calendar, what would it be called and when?",
    "If you could grant one stranger a single wish today, who and what would it be?",
    "If you could write a message in the sky with a plane, what would it say?",
    "If you had to live in a lighthouse for a year, what would you bring to survive?",
    "If you could create your own holiday tradition just for us, what would we do?",
    "If you could have any job from a children's book, which would you take?",
    "If you could rewrite a famous quote to make it funnier, which would you tweak?",
    "If you had a dragon as a companion, what would its name be and what would it eat?",
    "If you could design your own currency, whose face would be on it?",
    "If you could make a documentary about any mundane subject, what would it cover?",
    "If we could time-share any celebrity couple's house for a weekend, whose would we pick?",
    "If you could invent a robot to do one thing forever, what would it handle?",
    "If you could have a secret power nobody knew about, what would stay hidden?",
    "If you could teleport one smell from your childhood back to today, which would it be?",
    "If you had to wear one outfit for the rest of your life, what would it look like?",
    "If you could ride any animal like a horse, which would you saddle up?",
    "If you could eavesdrop on any conversation in history, which would you listen to?",
    "If you could convince the world to adopt one weird habit, what would you spread?",
    "If you could make any season last forever, which would you choose and where?",
    "If you could star in a cereal commercial, what would the cereal be called?",
    "If you could build a secret underground lair, what would be the entrance disguised as?",
    "If you could host a dinner party with villains only, who would you invite?",
    "If you had to invent a new Olympic event using household items, what would it be?",
    "If you could see one prediction about the year 2100 come true, what would it be?",
    "If you had to perform at a talent show tonight, what would your act be?",
    "If you could leave footprints that glowed wherever you walked, what color would they be?",
    "If you could replace your voice with any sound effect, what would come out of your mouth?",
    "If we could co-write a children's book tonight, what would it be about?",
    "If you could build a sandwich with any three ingredients in history, what would be stacked?",
    "If you could have your own catchphrase, what would it be?",
    "If you could pick one fictional planet to vacation on, where would you beam down?",
    "If you could make one boring thing magical, what would you enchant?",
    "If you could start a band with anyone alive today, who is in the lineup?",
    "If you could have one hidden talent suddenly revealed, what would you want it to be?",
    "If you discovered a new island, what would you name it and what rules would it have?",
    "If you had to write your autobiography tonight, what would the title be?",
    "If you could be the mascot for any sports team, which would you represent?",
    "If you could only communicate through drawings for a day, how would you tell me you love me?",
    "If you could have any mythical weapon, what would you wield and for what quest?",
    "If you could make up a brand new saying, what nonsense would you popularize?",
    "If you could give one historical figure a cell phone for a day, who gets it?",
    "If you could become a character in a Studio Ghibli film, which one would you join?",
    "If you could hear what any one person was thinking right now, who would it be?",
    "If you had to pitch a new flavor of soda, what would it taste like?",
    "If you could have a personal theme park ride just for you, what would it do?",
    "If you could own any famous painting, which would hang in our kitchen?",
    "If you had to be trapped in an elevator with one fictional character, who would you pick?",
    "If you could make one thing in life automatic forever, which chore is gone?",
    "If you could design a new zoo exhibit, what unlikely creatures would live together?",
    "If you had a talk show just for pets, who would your first guest be?",
    "If you could host the Olympics in any location, real or imaginary, where would it be?",
    "If you could build a snowman that came to life, what would his personality be like?",
    "If you could live inside a snow globe, what would the scene be?",
    "If you could trade places with any animal for a day, what would you be?",
    "If you could give a pep talk to the entire planet for two minutes, what would you say?",
    "If you could bring one fictional food into reality, what would you take a bite of first?",
    "If you had to make a documentary about me, what would the title be?",
    "If you could send one emoji back to medieval times, which would cause the most chaos?",
    "If you could swap our pet for any wild animal, which would we adopt?",
    "If you had to choose a dance style to communicate with for life, which would it be?",
    "If you could invent a new sport using only pillows, what would it look like?",
    "If you could taste a color, which would taste the sweetest?",
    "If we started a podcast tomorrow, what would our first episode be about?",
    "If you had to decorate our home in one theme forever, what mood would it be?",
    "If you could learn any outdated job from centuries ago, what would you master?",
    "If you could swap the sun with any other star, which would light up our days?",
    "If you could send one text to anyone in history, what would it say?",
    "If you could live in any fictional small town, which one would you call home?",
    "If you could only eat foods that start with one letter forever, what letter wins?",
    "If you could rewrite the rules of a board game to be wild, which would you remix?",
    "If you had to choose a smell to follow you everywhere, what would it be?",
    "If you could invent your own currency for our relationship, what would it be worth?",
    "If you could be a contestant on any game show from history, which would you pick?",
    "If you could hide a treasure somewhere for strangers to find, what would it be?",
    "If you could bottle one childhood memory and keep it on a shelf, which would it be?",
    "If you could design a secret handshake for us, how many steps would it have?",
    "If you could build an entire city from scratch, what would it be most famous for?",
    "If you could give one chore superpowers, what would dishwashing be able to do?",
    "If you could join any fictional crew on an adventure, whose ship would you board?",
    "If you could wear a cape everywhere without judgment, what color and style?",
    "If you could start a tradition that lasts 500 years, what would it be?",
    "If you could add a new room to any famous landmark, what would it hold?",
    "If you could turn any boring object into your sidekick, what would it be?",
    "If you could take a class taught by anyone, living or fictional, who teaches you?",
    "If you could swap one of your memories with a stranger's, which would you trade?",
    "If you had a time machine but could only visit Tuesdays, which Tuesday would you visit?",
    "If you could rename any planet, which would you rechristen and what to?",
    "If you could inherit one trait from any animal, which would you take?",
    "If you could design a new Olympic medal, what would it look like and smell like?",
    "If you could transform one daily object into a portal, which would it be and to where?",
    "If you could give every person a tiny magical power, what small magic would it be?",
    "If you could invent a holiday just for couples, what would we celebrate and how?",
    "If you could turn our love story into a ride at Disneyland, what would it be called?",
    "If you could host a cooking show with any chef, dead or alive, who is plating up?",
    "If you could invent a new word and force it into the dictionary, what does it mean?",
    "If you could relive your wedding day with one small change, what would you tweak?",
    "If you could invent an app that solves one tiny problem, what would it do?",
    "If you could fall asleep and dream the same dream every night, what would it be?",
    "If you could walk one red carpet event of your choosing, which would it be?",
    "If you could cast a spell on our future selves right now, what would it do?"
  ],

  childhood: [
    "What is the most vivid memory you have from before age 10?",
    "What game or activity were you absolutely obsessed with as a kid?",
    "Tell me about your best friend when you were little. Are you still in touch?",
    "What was the first thing you ever saved up your own money to buy?",
    "Describe the house you grew up in. Which room was your favorite?",
    "What is the most trouble you ever got into as a kid?",
    "What did you want to be when you grew up? When did that dream change?",
    "What was your favorite family tradition growing up?",
    "What was the first movie or show that absolutely blew your mind as a child?",
    "Tell me about a teacher who made a real impact on you.",
    "What was your favorite hiding spot when you were young?",
    "What is a food you loved as a kid but cannot stand now, or vice versa?",
    "What was your most embarrassing moment in school?",
    "Did you have a childhood crush? Tell me the story.",
    "What was the bravest thing you did as a kid?",
    "Tell me about a birthday you remember really well. What made it special?",
    "What was your favorite thing to do during summer break?",
    "Did you have a stuffed animal or toy you were inseparable from? What was its name?",
    "What was your favorite bedtime story or the one you asked for over and over?",
    "Tell me about a family road trip or vacation from when you were young.",
    "What is a lesson your parents taught you that you still carry with you?",
    "What was your first pet? Tell me everything about them.",
    "What was the first concert, play, or big event you ever attended?",
    "Tell me about a time you stood up for someone when you were young.",
    "What was the weirdest phase you went through as a teenager?",
    "What is a smell that instantly takes you back to your childhood?",
    "Tell me about the neighborhood you grew up in. What made it special?",
    "What was the first album or song you were completely obsessed with?",
    "What was your favorite subject in school and why?",
    "Tell me about a moment from your childhood that shaped who you are today.",
    "What was your favorite hiding spot as a kid, and who were you hiding from?",
    "Tell me about a meal your grandmother or grandfather made that you still crave.",
    "What was the first movie that genuinely scared you, and how old were you?",
    "Describe your childhood bedroom in as much detail as you can remember.",
    "What is a family tradition you hope we carry on together someday?",
    "Who was your first crush, and what did you do to try to impress them?",
    "Tell me about a time you got lost as a kid. How did it end?",
    "What was the weirdest thing you genuinely believed as a child?",
    "Describe your favorite birthday party you ever had growing up.",
    "What was the song your family played constantly when you were young?",
    "Tell me about a teacher who completely changed the way you saw yourself.",
    "What childhood pet do you still miss, and what made them special?",
    "What was the first concert, show, or live event your parents took you to?",
    "Describe a summer day from your childhood that felt like it lasted forever.",
    "What was your favorite meal as a kid that you would request for special occasions?",
    "Tell me about the first time you ever flew on an airplane.",
    "Who was the neighborhood kid everyone was a little afraid of?",
    "What was the most embarrassing thing you ever wore to school?",
    "Describe the playground you spent the most time at growing up.",
    "What was your go-to order at the family restaurant you visited most often?",
    "Tell me about the first book that made you cry.",
    "What chore did you hate the most, and how did you try to get out of it?",
    "Describe your favorite Halloween costume you ever wore.",
    "What was the best gift you ever received as a child?",
    "Tell me about a time you broke something valuable and tried to hide it.",
    "Who taught you how to ride a bike, and where did you learn?",
    "What was the nickname your family called you that nobody else knew?",
    "Describe a snow day, rainy day, or sick day that felt magical.",
    "What was the first thing you wanted to be when you grew up?",
    "Tell me about a sibling fight that still makes you laugh.",
    "Who was the adult in your life you most wanted to be like?",
    "What was the game you invented or played obsessively with your siblings or friends?",
    "Describe the town or neighborhood you grew up in to someone who has never been.",
    "What was your most prized possession as a kid?",
    "Tell me about the first time you stayed up all night.",
    "What was a food you hated as a kid that you secretly love now?",
    "Describe a family vacation that didn't go as planned.",
    "What was the first secret you ever kept from your parents?",
    "Tell me about the art, poem, or project you were most proud of in school.",
    "Who was your childhood best friend, and what made your bond unique?",
    "What show did you rush home from school to watch?",
    "Describe a moment you felt like the coolest kid in the world.",
    "What was your favorite book series, and which character did you relate to?",
    "Tell me about a time you got in trouble for something you didn't do.",
    "What was the strangest thing in your grandparents' house?",
    "Describe your parents' car and a memory of being in the backseat.",
    "What was the first sport or activity you tried, and did you stick with it?",
    "Tell me about a childhood fear you outgrew.",
    "Who was your favorite fictional character growing up, and why?",
    "What was the most daring thing you and your friends ever dared each other to do?",
    "Describe the kitchen of the house you grew up in.",
    "What was a lie you told as a kid that you still remember?",
    "Tell me about a moment your parents surprised you.",
    "What was the first time you realized adults didn't know everything?",
    "Describe your favorite after-school snack ritual.",
    "What was the strangest rumor that went around at your school?",
    "Tell me about a time you made your parents laugh really hard.",
    "What was your bedroom wall covered in as a kid?",
    "Describe your earliest memory of feeling truly proud of yourself.",
    "What was the first thing you remember saving a secret stash of?",
    "Tell me about the holiday dinner moment that your family still talks about.",
    "Who was the family member you confided in when you couldn't tell anyone else?",
    "What was your favorite thing about your grandparents' house?",
    "Describe a childhood hobby that consumed all your free time.",
    "What was a movie you watched over and over again until the tape wore out?",
    "Tell me about the first time you felt betrayed by a friend.",
    "What was the rule in your house that you found ridiculous as a kid?",
    "Describe your favorite teacher and what made them memorable.",
    "What was the smell of your childhood home?",
    "Tell me about a family member who told the best stories.",
    "What was the first time you remember feeling heartbroken?",
    "Describe a summer camp, class trip, or sleepover that changed something in you.",
    "What was your favorite toy, and what happened to it?",
    "Tell me about a moment you felt seen by an adult for the first time.",
    "What was the backyard, park, or woods where you had your biggest adventures?",
    "Describe a family car trip memory that sticks with you.",
    "What was the weirdest collection you had as a kid?",
    "Tell me about a time you snuck out or stayed up past your bedtime.",
    "What was the first thing that ever made you feel like a grown-up?",
    "Describe the first wedding or big family event you remember attending.",
    "What was your favorite breakfast growing up?",
    "Tell me about a neighbor who was a big part of your childhood.",
    "What was the most magical thing about Christmas, Hanukkah, or another holiday in your family?",
    "Describe a moment a friend stood up for you when you needed it.",
    "What was the game at recess that everyone wanted to play?",
    "Tell me about a time you felt like you didn't belong as a kid.",
    "What was the most extravagant thing you asked Santa or a gift-giver for?",
    "Describe your walk or ride to school.",
    "What was the first movie you saw in a theater?",
    "Tell me about a time you stood up for yourself as a kid.",
    "What was the strangest tradition your family had that you thought was normal?",
    "Describe your parents when they were younger through a child's eyes.",
    "What was your favorite holiday dessert that only appeared once a year?",
    "Tell me about the first time you got to stay home alone.",
    "Who was the first friend who made you feel truly understood?",
    "What was the bedtime routine your parents had with you?",
    "Describe a time an adult made you feel really small.",
    "What was the coolest thing in your house that belonged to someone else?",
    "Tell me about a childhood dream you had that felt prophetic.",
    "What was the first time you realized your family was different from others?",
    "Describe a moment you felt completely free as a kid.",
    "What was your favorite board game or card game growing up?",
    "Tell me about a time you stood up to a bully, or wish you had.",
    "What was the biggest thing you were ever jealous of as a kid?",
    "Describe a family recipe that only existed in your house.",
    "What was the first real loss you experienced?",
    "Tell me about a trip to the doctor, dentist, or hospital that you still remember.",
    "What was your go-to excuse for getting out of something you didn't want to do?",
    "Describe the sound of your childhood home when everyone was there.",
    "What was the most exciting day of the school year for you?",
    "Tell me about a childhood friendship that ended mysteriously.",
    "What was the first piece of clothing you picked out for yourself?",
    "Describe a moment you discovered something about your parents that surprised you.",
    "What was the weirdest thing you ever ate on a dare?",
    "Tell me about the TV commercial, jingle, or theme song that lives in your head.",
    "What was the biggest mess you ever made as a kid?",
    "Describe your first real sleepover.",
    "What was the first time you felt genuinely homesick?",
    "Tell me about a moment a teacher embarrassed you in front of the class.",
    "What was the most creative thing you built, drew, or made as a kid?",
    "Describe a family member whose laugh you can still hear.",
    "What was the school subject you secretly loved?",
    "Tell me about a time your imagination got carried away.",
    "What was the rule you broke the most often?",
    "Describe a place from your childhood you'd love to show me someday.",
    "What was your favorite thing about the first day of school?",
    "Tell me about a time you made a new friend in an unexpected place.",
    "What was the food at school you actually looked forward to?",
    "Describe the first time you remember feeling really grown-up fancy.",
    "What was the first song you learned all the words to?",
    "Tell me about a time you tried to run away from home.",
    "What was your favorite thing to do on a rainy day?",
    "Describe a moment your parent did something that felt heroic.",
    "What was the strangest place you ever fell asleep as a kid?",
    "Tell me about the first crush who noticed you back.",
    "What was the most embarrassing thing a family member did in public?",
    "Describe a summer job, chore, or hustle you had as a kid.",
    "What was the first book you read that felt like it was written just for you?",
    "Tell me about a time you got caught doing something you shouldn't have.",
    "What was your favorite way to spend a Saturday morning?",
    "Describe a moment you felt the whole world was watching you.",
    "What was the treat you got only when you were sick?",
    "Tell me about the strangest dream you remember from childhood.",
    "What was the first thing you ever built with your hands?",
    "Describe the friend group you were part of in middle school.",
    "What was the biggest lie an adult ever told you?",
    "Tell me about a moment you felt really close to one of your parents.",
    "What was the style phase you went through that mortifies you now?",
    "Describe a place where you felt completely safe as a kid.",
    "What was the prank you pulled, or had pulled on you, that you'll never forget?",
    "Tell me about the first time you remember feeling jealous.",
    "What was your earliest memory involving water — a pool, ocean, lake, or bath?",
    "Describe a moment your sibling, cousin, or friend saved you from something.",
    "What was the family story that always got told at gatherings?",
    "Tell me about a time you felt misunderstood by the adults around you.",
    "What was your favorite thing about your grandparents specifically?",
    "Describe the worst haircut you ever had.",
    "What was the first thing you remember wanting to be really good at?",
    "Tell me about a time your parents fought and what you did.",
    "What was your happy place as a kid?",
    "Describe a moment you felt completely understood by someone.",
    "What was the object at a relative's house that fascinated you?",
    "Tell me about the first thing you remember learning and loving.",
    "What was the school event you looked forward to all year?",
    "Describe a time you got away with something you shouldn't have.",
    "What was a phrase your family said that nobody outside your house understood?",
    "Tell me about a childhood injury and the story behind the scar.",
    "What was the first time you felt really, truly disappointed in someone?",
    "Describe your favorite weekend ritual growing up.",
    "What was the oldest person you knew as a kid, and what did they teach you?",
    "Tell me about a time you were absolutely convinced something magical had happened.",
    "What was the first time you remember feeling genuinely in love with anything?",
    "Describe a family member who was larger than life.",
    "What was the neighborhood legend or scary story where you lived?",
    "Tell me about a gift you gave someone as a kid that you were so proud of.",
    "What was the thing you collected, traded, or hoarded as a kid?",
    "Describe the moment you realized you were growing up.",
    "What was the weirdest thing your family did on vacation?",
    "Tell me about a time a stranger was unexpectedly kind to you.",
    "What was your earliest memory of music moving you?",
    "Describe a childhood photo of yourself that says everything about who you were.",
    "What was the first time you ever won something?",
    "Tell me about the friend you wish you had stayed in touch with.",
    "What was the most you ever cried as a kid, and what was it about?",
    "Describe a moment that made you feel brave for the first time.",
    "What was the thing that you and your best friend always did together?",
    "Tell me about an object in your childhood home you'd want to keep forever.",
    "What was the candy, drink, or snack that defined your childhood?",
    "Describe a time your curiosity got you in trouble.",
    "What was the show, movie, or book that shaped your personality most?",
    "Tell me about an adult you were scared of, and whether that fear was fair.",
    "What was the trip you begged your parents to take you on?",
    "Describe the first time you remember really, truly laughing so hard it hurt.",
    "What was the thing you always wanted to do 'when you were older'?",
    "Tell me about a moment you were the hero of your own story as a kid.",
    "What was a piece of advice from a grandparent that has stuck with you?",
    "Describe the most peaceful moment of your childhood.",
    "What was the first real responsibility you were given?",
    "Tell me about a time you stayed up late with someone you loved.",
    "What was the first adult thing you remember doing and feeling proud of?",
    "Describe a time you felt genuinely left out as a kid.",
    "What was your version of 'making a deal' with your parents growing up?",
    "Tell me about a time you discovered something about yourself that felt important.",
    "What was the story behind your name, and how did you feel about it as a kid?",
    "Describe a childhood moment you wish you could relive just one more time."
  ],

  spicy: [
    "What was your very first impression of me when we met? Be honest.",
    "What is something I do that drives you crazy in the best way?",
    "Describe a moment between us that still gives you butterflies.",
    "What is a date we have not been on yet that you have been secretly wanting?",
    "If you could relive one intimate moment between us, which one would you choose?",
    "What is something you find attractive about me that you have never told me?",
    "What song makes you think of me and why?",
    "What was going through your mind right before our first kiss?",
    "What outfit or look of mine makes it hardest for you to concentrate?",
    "What is a fantasy date night you have imagined but never brought up?",
    "Where is the most adventurous place you would want us to be intimate?",
    "What is the most attractive thing I have ever said to you?",
    "If we had a whole weekend alone with no responsibilities, how would you want to spend it?",
    "What is a secret turn-on you have not shared with me yet?",
    "Describe the perfect way for me to seduce you.",
    "What physical feature of mine are you most drawn to and why?",
    "What is something new you want us to try together in the bedroom?",
    "What is the most memorable compliment I have ever given you?",
    "If you could set the scene for the perfect romantic evening, what would it look like?",
    "Tell me about a time you wanted to kiss me but held back. What stopped you?",
    "What do I do in everyday life that you find unexpectedly attractive?",
    "What is a word or phrase I say that sends shivers down your spine?",
    "If you could choreograph our perfect slow dance, what song would play?",
    "What is the boldest thing you wish I would do more often?",
    "Describe your favorite way to be touched without using the word 'touch'.",
    "What is a romantic movie scene you wish we could recreate?",
    "What was the moment you knew the physical chemistry between us was real?",
    "If you could read my mind for just one moment, which moment would you choose?",
    "What is the most romantic text or message I have ever sent you?",
    "Tell me something you want to whisper to me but have been too shy to say.",
    "What was the exact moment you realized you were falling for me?",
    "Which of my features do you catch yourself staring at when I'm not looking?",
    "What is the most romantic thing you've ever imagined us doing together?",
    "Describe the kiss of ours that lives rent-free in your head.",
    "What is something about my laugh that does something to you?",
    "If you could plan a surprise weekend just for us, where would we wake up?",
    "What is a song that instantly reminds you of us?",
    "What little thing I do sends butterflies straight through you?",
    "When was the last time I made your heart skip a beat, and why?",
    "What is one compliment about me you think but rarely say out loud?",
    "Describe the outfit you most secretly love seeing me in.",
    "What part of our morning routine feels the most intimate to you?",
    "What is a fantasy date you have been quietly dreaming up for us?",
    "When did you first feel truly, undeniably drawn to me?",
    "What scent, smell, or fragrance of mine drives you a little wild?",
    "What is a small gesture of mine that melts you every time?",
    "Describe the way you want to be kissed tonight.",
    "What is something you find mysterious and sexy about me?",
    "What is a look I give you that you never want me to stop giving?",
    "If we had a whole rainy day in bed, how would you want to spend it?",
    "What is something sweet you once thought about me but never shared?",
    "Which of my smiles is your absolute favorite?",
    "What is a memory of ours that still gives you goosebumps?",
    "Where on my body do you love being kissed the most?",
    "What is a moment you wish we could freeze in time forever?",
    "What was the first thing that physically attracted you to me?",
    "Describe a slow dance you would love for us to share.",
    "What is something you secretly love about the way I touch you?",
    "If I wrote you a love letter tonight, what would you hope it said?",
    "What is a place on me you love resting your head or hand?",
    "What is the most thoughtful flirty thing I've ever done for you?",
    "What do you daydream about when your mind wanders to me?",
    "What is a fantasy vacation you would want the two of us to take?",
    "Describe a moment where I caught you off guard with my charm.",
    "What is your favorite way for me to say your name?",
    "What kind of kiss have we not shared enough of lately?",
    "What is something playful you have wanted to try with me?",
    "What is the sexiest thing about my confidence?",
    "What is a secret nickname you've thought about calling me?",
    "Describe a candlelit evening you wish we could recreate or invent.",
    "What is one thing about my eyes that draws you in?",
    "What is a gesture I make that feels deeply romantic to you?",
    "If tonight were our first night together all over again, what would you do?",
    "What is something you miss about the early days of us?",
    "What is a tiny ritual between us that feels sacred?",
    "Describe the feeling of our very first touch.",
    "What is your favorite memory of us being lost in conversation?",
    "What is something about my body that surprises you in the best way?",
    "What is a look I wear that makes you forget what you were saying?",
    "If we ran away for a night, where would you take me?",
    "What is the last thing that made you think, 'I'm so lucky'?",
    "What is one way you have been wanting to be pampered by me?",
    "Describe a slow morning together that sounds like heaven to you.",
    "What is one thing that makes our chemistry feel one-of-a-kind?",
    "What is a sweet thing I whispered that you have never forgotten?",
    "What is your favorite kind of flirting between the two of us?",
    "If you could freeze one sunset with me, where would it be?",
    "What part of our goodbyes feels the most tender to you?",
    "What is the most romantic setting you can picture us in right now?",
    "Describe the ideal home date night you have been craving with me.",
    "What is something about my voice that turns you on?",
    "What is a compliment you wish I gave you more often?",
    "What is a moment when you wanted to kiss me but held back?",
    "What do you love most about the way I hold you?",
    "What is one thing you think is criminally underrated about me?",
    "If you could read my mind for an hour, what would you most want to know?",
    "What is a playful dare you have been wanting to give me?",
    "Describe the dress, shirt, or outfit you'd love to see me in next.",
    "What is the most attractive thing I did this past week?",
    "What is a little habit of mine you secretly adore?",
    "What song would you want playing during our most intimate moment?",
    "What is a kiss you'd love to have again exactly the way it happened?",
    "What is a trip for just the two of us that is calling your name?",
    "If I planned a surprise evening, what would you hope it included?",
    "What is the most seductive thing about how you see me?",
    "Describe a fantasy weekend getaway for just us, in detail.",
    "What is something about my personality that you find irresistible?",
    "What is a small touch from me that always feels electric?",
    "What do you think our first date said about us as a couple?",
    "What is your favorite kind of eye contact between us?",
    "What is a romantic moment you've secretly been wanting to create?",
    "Describe the way you feel when I walk into a room.",
    "What is something I could wear right now that would stop you in your tracks?",
    "What is a trait of mine that feels almost too good to be true?",
    "If we had no phones for a whole weekend, how would we fill it?",
    "What is one adventure you have been quietly hoping we'd take together?",
    "What is the first thing you notice about me every morning?",
    "Describe an intimate moment you want to recreate with me soon.",
    "What is something you have always wanted me to do more of?",
    "What memory of us makes you blush the most?",
    "What is your favorite way to be pulled close by me?",
    "What is a movie scene you wish we could step into together?",
    "If you designed the perfect date for us, what would it look like?",
    "What is a moment you remember where our chemistry felt undeniable?",
    "What is something about our relationship that feels like magic to you?",
    "What is a sweet confession you have been sitting on?",
    "What is one thing about my style or fashion that draws you in?",
    "What is a small but unforgettable moment we've shared?",
    "Describe the most romantic thing I've ever said to you.",
    "What does your ideal slow, lazy Sunday with me look like?",
    "What is a part of me that you find completely disarming?",
    "What was the first 'oh wow' moment you had about me?",
    "What is a sound I make that melts you a little?",
    "What is something you wish we did more often to stay connected?",
    "If you could write a love note on my mirror, what would it say?",
    "What is the sexiest thing I do without even realizing it?",
    "What is a tiny thing I do that makes you feel seen?",
    "Describe the mood you want our next date night to have.",
    "What is something I'm wearing right now that you find attractive?",
    "What is a memory of mine you wish you had been there for?",
    "What do you love about the way I flirt with you?",
    "What is one small adventure you'd plan for us this weekend?",
    "What is the last thing that made you think about me all day?",
    "What is a moment I caught you looking, and you didn't mind?",
    "What is your favorite kind of hug from me?",
    "Describe a tender moment between us that still stays with you.",
    "What is a question you've always wanted to ask me but never have?",
    "What is something about our first months that you miss?",
    "If we could disappear anywhere right now, where would you take me?",
    "What is a romantic film moment you'd love to recreate with me?",
    "What is a song lyric that reminds you of how you feel about me?",
    "What is the most charming thing about the way I speak?",
    "What is something about our connection you've never fully put into words?",
    "If you could plan a flirty surprise for me, what would it be?",
    "What is a part of my laugh that you find utterly adorable?",
    "What is an intimate moment you have been hoping for lately?",
    "What is the sweetest thing you've ever thought while watching me sleep?",
    "Describe the kind of kiss that would be perfect right now.",
    "What is something about the way I dress that turns your head?",
    "What is a scenario between us you've played out in your mind?",
    "What is the most romantic place we could be on vacation together?",
    "What is something I do that makes you feel completely safe?",
    "What is a moment you knew you wanted forever with me?",
    "What is your favorite thing I've ever whispered to you?",
    "What is something about my confidence that you find sexy?",
    "If we had a whole night with no plans, what would you choose?",
    "What is something new you'd like us to try on date night?",
    "What is a look or style of mine you'd love me to bring back?",
    "Describe the moment you first realized you were really into me.",
    "What is something about my hands that you love?",
    "What is a romantic memory that always makes you smile?",
    "What is a small way I could make your heart flutter tonight?",
    "What is an outfit of yours you'd love me to react to?",
    "What is a moment we've shared that felt like a movie scene?",
    "What is the most flirty text you have ever wanted to send me?",
    "Describe your idea of a perfectly romantic evening at home.",
    "What is a tiny thing about me that you find unexpectedly attractive?",
    "What is the most thoughtful thing I've ever done for you romantically?",
    "If our love had a scent, what do you imagine it would be?",
    "What is a part of our intimacy you want to slow down and savor?",
    "What is something about the way I look at you that you cherish?",
    "If you could design our dream bedroom for tonight, what would it include?",
    "What is a cozy activity you'd love us to share under a blanket?",
    "What is something you find enchanting about the way I move?",
    "What is a memory of us dancing together that you love?",
    "What do you love most about our private inside jokes?",
    "What is something about our late-night talks that you treasure?",
    "Describe the version of me that made you fall hardest.",
    "What is a romantic tradition you'd love for us to start?",
    "What is something you think is sexy about the way I listen?",
    "What is a place you imagine us kissing that we haven't yet?",
    "What is a moment you caught yourself thinking 'they're mine'?",
    "What is something you wish I had done on our first date?",
    "If our chemistry were a flavor, what would it taste like?",
    "What is a secret compliment you've been saving up for me?",
    "What is something I did recently that reminded you why you chose me?",
    "Describe the perfect lazy afternoon between us.",
    "What is one thing about my body language that draws you in?",
    "What is a love letter moment I could create for you tonight?",
    "What is something I wear to bed that you find adorable?",
    "What is the most irresistible thing about how I smile at you?",
    "What is a romantic fantasy you've never shared with anyone?",
    "What is a memory of us laughing that feels the most us?",
    "If I planned a mystery date for you, what would you hope it was?",
    "What is something we've done together that felt effortlessly romantic?",
    "What is a small gesture I could make right now that would mean everything?",
    "What do you find most magnetic about my personality?",
    "What is a side of me you've glimpsed that you want to see more of?",
    "What is your favorite way for us to fall asleep together?",
    "What is a moment that made you feel completely seen by me?",
    "Describe the way you'd want to be welcomed home by me tonight.",
    "What is something about our first week together that still glows?",
    "What is one thing you love about how we flirt even after all this time?",
    "What is a romantic surprise you'd love to receive from me?",
    "What is the most attractive thing about how I carry myself?",
    "What is a little moment of ours that felt like a secret?",
    "What is a kiss location you'd love us to try for the first time?",
    "What is something about my touch that calms you instantly?",
    "Describe the most romantic compliment you could imagine from me.",
    "What is a playful promise you'd like to make me tonight?",
    "What is a part of our story you love telling the most?",
    "What is something about me that still makes you feel curious?",
    "What is a flirty memory from early on that you still replay?",
    "What is a quality about me that feels dangerously attractive?",
    "What do you think is our most romantic time of day together?",
    "What is a photo of us that captures exactly how you feel about me?",
    "What is something tender you'd love to hear from me right now?",
    "What is a moment you felt our connection was almost magnetic?",
    "If we wrote our love story into a novel, what would the opening line be?",
    "What is a small romance I could sneak into your day tomorrow?",
    "What is one way my attention makes you feel?",
    "What is a memory of our hands intertwined that stays with you?",
    "What is a whispered secret you've been wanting to share with me?"
  ],

  dreams: [
    "What is one thing on your bucket list you have not told anyone about?",
    "If money were no object, what would our life look like in 10 years?",
    "What skill or hobby do you wish you could master overnight?",
    "If we could design our dream home together, what is the one non-negotiable feature?",
    "What adventure do you want us to have together in the next year?",
    "If you could wake up tomorrow having gained one ability, what would it be?",
    "Where do you see yourself at 80, and what do you hope you will have done by then?",
    "What is something you have always wanted to learn but keep putting off?",
    "If you could start a business with no risk of failure, what would it be?",
    "What is a place you have never been but feel like you are meant to visit?",
    "If you could change one thing about how you spend your days, what would it be?",
    "What is a dream you had as a child that you still quietly hold onto?",
    "If we won the lottery tomorrow, what is the very first thing you would want to do?",
    "What kind of legacy do you want to leave behind?",
    "If you could spend a year doing absolutely anything, what would your year look like?",
    "What is a fear you want to conquer in the next five years?",
    "If we could take a sabbatical together, where would we go and what would we do?",
    "What does your ideal regular Tuesday look like in five years?",
    "What is something you want to build, create, or make with your own hands?",
    "If you could guarantee one thing about our future, what would it be?",
    "What is a cause or mission you feel passionate about and want to do more for?",
    "If you could live in any city in the world for a year, which one?",
    "What do you hope people say about you when you are not in the room?",
    "What is something you want us to accomplish together as a team?",
    "If you could write a book about anything, what would it be about?",
    "What does retirement look like in your imagination?",
    "What is a tradition you want to start in our life together?",
    "If you had a year off and unlimited funds for education, what would you study?",
    "What is the wildest dream you have that you think might actually be possible?",
    "Where do you want to be on your next birthday, and who do you want there?",
    "What country have you always dreamed of living in for at least a year?",
    "If we could take a six-month sabbatical together, how would we spend it?",
    "What is one adventure you hope we take before we turn 40?",
    "What does your ideal morning routine look like five years from now?",
    "If you could have dinner with your future self, what would you want to ask?",
    "What is a dream you have quietly carried since childhood?",
    "If we built a vacation home anywhere in the world, where would it be?",
    "What is one legacy you hope to leave behind for future generations?",
    "What chapter of your life are you most excited to start writing?",
    "If you could master any instrument overnight, which would it be and why?",
    "What is a place on earth you absolutely need to see before you die?",
    "How do you picture our life together when we are in our seventies?",
    "What is one career pivot you have secretly been considering?",
    "If we could raise our future kids anywhere, where would you pick?",
    "What is a hobby you want us to take up together this year?",
    "What would your dream garden or backyard look like one day?",
    "If you wrote a memoir at 90, what would the title be?",
    "What does financial freedom mean to you in concrete terms?",
    "What is one language you want to learn fluently before you die?",
    "If we could volunteer anywhere for a cause, what would you choose?",
    "What does a perfect weekend look like for us ten years from now?",
    "What is a skill you want to pass down to the next generation?",
    "If you could design the perfect retirement, what would a Tuesday look like?",
    "What is one tradition you want us to start as a couple?",
    "If we wrote a bucket list together tonight, what goes at the top?",
    "What is a childhood dream you are still chasing in some form?",
    "If we could live off-grid for a year, where would we go?",
    "What does your dream workspace look like?",
    "What is one creative project you hope to finish in your lifetime?",
    "If we could take one trip every year forever, where would the first be?",
    "What is something you hope is true about the world by 2050?",
    "If you could found a nonprofit, what cause would it serve?",
    "What does your ideal version of aging gracefully look like?",
    "If we could adopt any kind of pet in any setting, what would you pick?",
    "What is one bold move you want to make in the next two years?",
    "If we had a treehouse together, what would be inside it?",
    "What is a subject you wish you had studied in school?",
    "What small daily ritual do you hope we still share at 80?",
    "If we designed our own festival together, what would it celebrate?",
    "What is one physical challenge you want to conquer someday?",
    "If you could teach a class on anything, what would it be?",
    "What do you hope our future home smells like on a Sunday morning?",
    "If we could spend a month in any decade of history, which one?",
    "What is one fear about the future you want us to face together?",
    "If we could build a cabin from scratch, where would we build it?",
    "What is a book you hope to write one day, even in your head?",
    "If you could invent anything, what problem would it solve?",
    "What do you hope becomes true for us in the next twelve months?",
    "If we could sponsor a scholarship, who would we want to help?",
    "What is a piece of art you dream of owning someday?",
    "If we could have a second career in our fifties, what would yours be?",
    "What is a long-distance trail or hike you want us to attempt?",
    "If we could host a dinner party every month, who would we invite?",
    "What is one thing you want our future home to always have?",
    "If we could sail around the world, which ocean starts the journey?",
    "What is something you hope your friends will say about you in 30 years?",
    "If you could collect anything without limit, what would it be?",
    "What is one wild experiment you want to try in your life?",
    "If we could learn a craft together, what would it be?",
    "What is one place we should return to again and again for life?",
    "If we could open a small shop together, what would we sell?",
    "What is one cause you want us to champion as a couple?",
    "If we could take a year off when we are 50, how would we spend it?",
    "What do you hope our love looks like at its most mature?",
    "If we could throw a massive celebration one day, what would it honor?",
    "What is a skill you want to practice until you are truly great at it?",
    "If we could afford any education for our kids, what would it include?",
    "What is one landscape you want to wake up to at least once?",
    "If we launched a podcast together, what would it be about?",
    "What is a smell or taste you hope follows us through life?",
    "If we could set up a scholarship in our name, what would it fund?",
    "What is an achievement you want to earn by 40 or 50?",
    "If we lived on a farm together, what would we grow or raise?",
    "What is one dream you want to revisit that you once gave up on?",
    "If we could restore something old, what would it be?",
    "What is a charity you want to give generously to one day?",
    "If we could write a children's book together, what would it teach?",
    "What is the most beautiful stretch of road you want us to drive?",
    "If we could mentor young people, what would we teach them?",
    "What is one fashion or style you want to grow into with age?",
    "If we had unlimited weekends, what day trips would fill the year?",
    "What is a memory you want us to create in the next six months?",
    "If we could invent a tradition for our family, what would it be?",
    "What does success feel like to you, beyond money or status?",
    "If we could take up a sport together, what would it be?",
    "What is one way you want to grow as a partner this year?",
    "If we could remodel any one room in our future home, which one?",
    "What is a goal that would make this decade feel complete?",
    "If we could spend a summer somewhere new each year, where first?",
    "What is a lifestyle change you want us to make together?",
    "If we could record a family history, what would we start with?",
    "What is one piece of wisdom you hope to earn by 70?",
    "If we could take a pilgrimage anywhere, sacred or not, where?",
    "What is one courageous thing you want to do before next birthday?",
    "If we built a library together, what would be the first book?",
    "What is your wildest fantasy about where life could take us?",
    "If we could spend a winter somewhere warm each year, where?",
    "What is something you want to be known for in your community?",
    "If we could own a boat, what would we name it and where would we sail?",
    "What is a specific childhood place you want to take me one day?",
    "If we had a rooftop garden, what would be in it?",
    "What is an unconventional path you have secretly wanted to take?",
    "If we could host exchange students or travelers, who would we welcome?",
    "What is a memory from the future you can already picture vividly?",
    "If we could leave a time capsule for our great-grandkids, what is inside?",
    "What is a risk you want to take while we are still young enough?",
    "If we could have a second home anywhere, city or countryside?",
    "What is a physical place you want to be buried or scattered in?",
    "If we could be part of building something from scratch, what would it be?",
    "What is a superpower you wish you could develop in yourself?",
    "If we could spend a month in silence together, where would we go?",
    "What is one tradition from your family you want to carry forward?",
    "If we could invent a holiday for our future family, what is it?",
    "What is a dream you hope our kids or godchildren carry on for us?",
    "If we could take a long road trip together, what is the route?",
    "What is one way you want to use your talents in the next decade?",
    "If we could live in another country for five years, which one?",
    "What is a cause you want to leave money to in your will?",
    "If we could design a sanctuary for animals or people, what would it be?",
    "What is the next big leap you feel ready to take?",
    "If we could adopt one person's life philosophy, whose would it be?",
    "What is a family ritual you want us to create together?",
    "If we could grow old in any neighborhood we have ever visited, which?",
    "What is one improvement you want to make in your daily life this year?",
    "If we could throw our future selves a party, what would we celebrate?",
    "What is a place in nature that you want us to return to forever?",
    "If we could live through one invention in our lifetime, what would it be?",
    "What is one friendship you want to still have at 80?",
    "If you could gift one thing to the world, what would it be?",
    "What is a story from our life you hope we tell again and again?",
    "If we could invest in a young person's future, who comes to mind?",
    "What is a milestone you secretly hope we hit within five years?",
    "If we could open a retreat space, what would it focus on?",
    "What is something about our life together you hope never changes?",
    "If we could celebrate every anniversary somewhere new, what is year one?",
    "What is an ambitious dream you have been afraid to speak out loud?",
    "If we could give our future child one experience, what would it be?",
    "What is one personal breakthrough you want in the next year?",
    "If we had a dream car for long road trips, what would it be?",
    "What is a festival or event you want us to attend together someday?",
    "If we could save one tradition from going extinct, which one?",
    "What is a kindness you hope becomes second nature to you?",
    "If we could design our own wedding vow renewal, what would it look like?",
    "What is one creative risk you want to take before 50?",
    "If we could build a friend group over the next decade, who is in it?",
    "What is one thing you want us to do that most couples never do?",
    "If we had a yearly tradition that only we understood, what is it?",
    "What is one way you want your body to serve you well into old age?",
    "If we could attend any awards ceremony, which one and for what?",
    "What is a flavor or cuisine you want to master cooking?",
    "If we could take our parents on a dream trip, where would we go?",
    "What is a stage of life you are most looking forward to?",
    "If we could plant a forest together, where would it be?",
    "What is the one possession you want to own and keep forever?",
    "If we could take a year to study anything, what would you choose?",
    "What is a transformation you hope to see in yourself by 60?",
    "If we could start a small movement, what would it be about?",
    "What is a kind of love story you want ours to become?",
    "If we could build a life that is entirely quiet, would you take it?",
    "What is a pattern from your past you want to leave behind for good?",
    "If we could build a legacy in two words, what would they be?",
    "What is a challenging adventure you want us to survive together?",
    "If we could sponsor a village, school, or shelter, which would it be?",
    "What is a dream night under the stars you want us to have?",
    "If we could visit every country on one continent, which continent?",
    "What is a way you want to give back once we are more established?",
    "If we had a secret weekend ritual, what would it be?",
    "What is an instrument, tool, or machine you want to master?",
    "If we could invite our 20-year-old selves to dinner, what do we tell them?",
    "What is something you want to invent in your own small way?",
    "If we could live simply for a season, what would we let go of?",
    "What is an accomplishment that would make your younger self proud?",
    "If we could host our future grandkids every summer, what would we do?",
    "What is a craft you want to be buried with, metaphorically speaking?",
    "If we could design the perfect workweek, what would it look like?",
    "What is a photograph you dream of taking one day?",
    "If we could collaborate on one big project, what would we build?",
    "What is one hope you have for the next generation of your family?",
    "If we could have a small farm or homestead, what would we name it?",
    "What is a dream friendship circle you want to cultivate over time?",
    "If we could celebrate a midlife milestone boldly, what would it be?",
    "What is a comfort you want our future home to offer guests?",
    "If we could spend one year volunteering abroad, where would we serve?",
    "What is a part of yourself you want to develop more deeply?",
    "If we could open our own small business, what are its first hours?",
    "What is one ritual you want to share with our future children?",
    "If we could return to one country every year, which would it be?",
    "What is one thing you want to be financially free to say yes to?",
    "If we could attend a class together every month, what would it be?",
    "What is a lifestyle you want to try for just one year?",
    "If we could leave one message to the world, what would it say?",
    "What is one way you hope we keep surprising each other forever?",
    "If we could spend a summer writing or creating, what would we make?",
    "What is a belief you want to hold deeply by the time you are old?",
    "If we could pick one word to define our future, what would it be?",
    "What is one place you want us to call home at some point in our lives?",
    "If we could host a family reunion every five years, where would it be?",
    "What is a new version of yourself you want to meet one day?",
    "If we could take a month off every year, what would be our ritual?",
    "What is a dream you want to chase even if it takes 20 years?",
    "If we could each pick one skill for the other to learn, what would it be?",
    "What is an ending for our story you would love to write?"
  ],

  love: [
    "What is the smallest thing I do that makes you feel most loved?",
    "When did you first realize this was something more than a crush?",
    "What is one way I have changed you for the better?",
    "What is one thing I could do more often that would make your day?",
    "Describe a moment where you felt completely understood by me.",
    "What is the best compliment you have ever received from anyone?",
    "How do you know when you are loved? What does it feel like?",
    "What is something about our relationship that you are really proud of?",
    "What is a small act of love someone did for you that you never forgot?",
    "When do you feel most connected to me?",
    "What is something I do that you want to make sure I never stop doing?",
    "How did your parents show love to each other? How did that shape you?",
    "What does feeling safe in a relationship mean to you?",
    "What is your favorite memory of us that you replay in your head?",
    "What is something about me that you had to grow to appreciate?",
    "How do you most like to receive an apology?",
    "What is a moment when you felt incredibly grateful for us?",
    "What is your love language and when did you figure it out?",
    "What is something I have forgiven you for that meant a lot?",
    "How do you like to be comforted when you are having a bad day?",
    "What is a relationship lesson you learned the hard way?",
    "What is a quality in me that you hope to see in our future together?",
    "When was a time I made you feel like the most important person in the room?",
    "What does home feel like to you? Is it a place, a person, or a feeling?",
    "What is something you admire about how we handle disagreements?",
    "What is a vulnerability you have shared with me that brought us closer?",
    "What is a promise you want us to make to each other?",
    "What do you think is the secret to keeping love alive over the years?",
    "What is the kindest thing a stranger has ever done for you?",
    "If you could bottle one feeling from our relationship, which moment would it be from?",
    "What is the first memory you have of feeling truly loved by someone?",
    "When do you feel most emotionally safe with me?",
    "What is a word or phrase I say that always makes your heart soften?",
    "How did your family express love when you were growing up?",
    "What is one way you hope we love each other differently than our parents did?",
    "What does being cherished look like to you in everyday life?",
    "When was the last time you felt genuinely seen by me?",
    "What is a quiet ritual of ours that means more to you than it might seem?",
    "How do you like to be comforted when you are having a hard day?",
    "What is something I do that reminds you we are a team?",
    "When did you first feel like you could fully be yourself around me?",
    "What is a love story, real or fictional, that has shaped how you see us?",
    "What small gesture from me never fails to make you smile?",
    "How has your definition of love evolved since we met?",
    "What is one thing about our relationship you are most grateful for right now?",
    "When you picture us five years from now, what feels warmest to imagine?",
    "What is something I have taught you about love without realizing it?",
    "How do you know when I am feeling loved by you?",
    "What is a memory of us you return to when you need to feel at home?",
    "What does tenderness mean to you, and how do you like to receive it?",
    "When have you felt proudest to be with me?",
    "What is something you admire about how I move through the world?",
    "How do you think we have grown together in the last year?",
    "What is one way you feel braver because I am in your life?",
    "What is a moment when you realized you could trust me with something fragile?",
    "How did you learn to ask for what you need in love?",
    "What is a feeling you have with me that you have never had before?",
    "When do you feel most proud of us as a couple?",
    "What is something you hope I never stop doing?",
    "How do you like to be welcomed home at the end of a long day?",
    "What is one thing you think we do better than most couples?",
    "When have you felt most cared for by me in a season of difficulty?",
    "What is a compliment you received once that still lives inside you?",
    "How has loving me changed the way you love yourself?",
    "What is a song that sounds like how I make you feel?",
    "When do you feel the most connected to me without any words?",
    "What does emotional safety feel like in your body?",
    "What is a memory from our early days that you still treasure?",
    "How do you want to be loved on the days you find yourself hard to love?",
    "What is something you forgave yourself for because of our love?",
    "When did you last feel deeply understood by me without explaining?",
    "What is one way I make ordinary moments feel meaningful?",
    "How do you like to celebrate the small wins in life?",
    "What does devotion mean to you, and how do you want to live it out?",
    "When have you felt most at peace lying beside me?",
    "What is a way your love for me has surprised you?",
    "How can I make you feel more treasured in your everyday life?",
    "What is a lesson about love you hope we pass on to others?",
    "When did you first feel like our home was really a home?",
    "What is a small tradition of ours you never want to lose?",
    "How do you want to be held when you feel overwhelmed?",
    "What is something I do that makes you feel like the most important person in the room?",
    "When have you felt the softest version of yourself with me?",
    "What is a quality of mine you hope stays the same forever?",
    "How has being loved by me helped you heal something old?",
    "What is a moment where you felt our bond deepen quietly?",
    "When do you feel the most playful with me?",
    "What is a way you want us to keep falling in love over the years?",
    "How do you like to be encouraged when you are doubting yourself?",
    "What is something about our love that feels sacred to you?",
    "When have you felt most grateful to come home to me?",
    "What is a compliment you wish you heard more often?",
    "How has your idea of partnership shifted since being with me?",
    "What is a way I make you feel beautiful without saying so?",
    "When did you realize I was someone you could rely on?",
    "What is a memory of us laughing together that you love revisiting?",
    "How do you want to grow individually while staying close to me?",
    "What is something that makes you proud of the life we are building?",
    "When do you feel most inspired by me?",
    "What is a kindness of mine you have come to count on?",
    "How do you experience love in your body, not just your mind?",
    "What is a moment where you felt I truly had your back?",
    "When have you felt most nurtured by our relationship?",
    "What is a dream you feel braver pursuing because of us?",
    "How do you want us to care for each other as we age?",
    "What is a look of mine that makes you feel instantly loved?",
    "When did you realize love could be calm, not just thrilling?",
    "What is a way I make you feel like you are coming home to yourself?",
    "How has gratitude changed the way you show up in our relationship?",
    "What is a small thing we do daily that feels like love to you?",
    "When do you feel most emotionally close to me outside of big moments?",
    "What is a way we comfort each other that feels uniquely ours?",
    "How do you recognize love when it is quiet?",
    "What is one thing you hope I know without ever having to ask?",
    "When have you felt the most generous with your heart toward me?",
    "What is a habit of ours that keeps us close even when life is busy?",
    "How do you want to be celebrated on your birthday by me?",
    "What is a way I can show up better for you during stressful weeks?",
    "When have you felt most at ease being vulnerable with me?",
    "What is a part of me you hope I never hide from you?",
    "How has your heart softened since we have been together?",
    "What is a moment you felt you were exactly where you were meant to be?",
    "When do you feel my love without me having to say anything?",
    "What is a little luxury you would love us to share together?",
    "How do you want us to handle the hardest days gracefully?",
    "What is something I do that makes you feel chosen every day?",
    "When did you realize our love was something rare?",
    "What is a memory of your childhood home you want to recreate with me?",
    "How do you want to be reassured when you are feeling distant?",
    "What is one of the kindest things I have ever said to you?",
    "When do you feel the most cherished in our relationship?",
    "What is a way I surprise you in how I love you?",
    "How has our love taught you patience with yourself?",
    "What is a small act of service from me you appreciate deeply?",
    "When have you felt proudest of how we communicated through something hard?",
    "What is a gift I gave you that meant more than its size?",
    "How do you want us to keep growing spiritually or emotionally together?",
    "What is a moment of stillness with me you will never forget?",
    "When do you feel most confident because of our love?",
    "What is something small about me that you adore?",
    "How do you like to be loved in the morning hours?",
    "What is a phrase you would want engraved on something that represents us?",
    "When have you felt deeply held by me without any grand gesture?",
    "What is a way our love has made you more gentle with strangers?",
    "How do you receive love best when you are tired?",
    "What is a quality of our relationship you hope never fades?",
    "When did you realize I had become part of your sense of self?",
    "What is a memory of us that feels like a warm blanket?",
    "How would you describe the version of yourself that blooms around me?",
    "What is a way I make hard things feel lighter?",
    "When have you felt most spiritually connected to me?",
    "What is a promise you quietly make to me every day?",
    "How do you want us to take care of each other when we are sick?",
    "What is a kind of silence with me that feels like love?",
    "When do you feel the most honored by my words?",
    "What is a way you feel fuller as a person because of us?",
    "How has our love changed the way you see yourself in the mirror?",
    "What is a memory from this past year with me you want to preserve?",
    "When have you felt most accepted by me, flaws and all?",
    "What is something you love about our mornings together?",
    "How can I help you feel more appreciated this week?",
    "What is a value of mine you respect most?",
    "When do you feel most proud to call me yours?",
    "What is a way love feels different with me than it has before?",
    "How do you want us to grow wiser together over time?",
    "What is a moment between us that felt quietly extraordinary?",
    "When have you felt most at peace with who you are because of me?",
    "What is a memory of my voice that comforts you?",
    "How do you like to receive gratitude from me?",
    "What is something I do that makes you feel like a priority?",
    "When did you know our love was worth protecting?",
    "What is a dream you would love to build with me from scratch?",
    "How has forgiving each other made us stronger?",
    "What is a touch of mine that always grounds you?",
    "When have you felt most grateful for the way I listen?",
    "What is a way I help you feel braver in the world?",
    "How do you hope we love each other when we are old and gray?",
    "What is something tender about me that only you really see?",
    "When do you feel most yourself in our relationship?",
    "What is a story about us you love telling other people?",
    "How has being loved by you changed the way you love others?",
    "What is a moment when I made you feel truly special?",
    "When have you felt the warmth of home in a place that was not our house?",
    "What is a way I show up for you that you never take for granted?",
    "How do you want us to handle change with grace?",
    "What is a word you associate most with our love?",
    "When did you first feel proud of how we handle conflict?",
    "What is a way our love feels like a safe harbor to you?",
    "How do you want me to celebrate you more often?",
    "What is a quality of mine you hope rubs off on you?",
    "When do you feel most seen in your sadness by me?",
    "What is a way we have grown kinder together?",
    "How has our relationship made you more hopeful about life?",
    "What is a memory of us cooking, eating, or sharing food that you love?",
    "When have you felt most understood without saying a word?",
    "What is a way I help you come back to yourself?",
    "How do you want us to cultivate joy in our everyday life?",
    "What is a tiny habit of mine you find endearing?",
    "When do you feel most safe to cry in front of me?",
    "What is a lesson our love has taught you about patience?",
    "How do you want us to handle milestones and anniversaries?",
    "What is a way you feel cared for by me that you never expected?",
    "When have you felt most emotionally nourished in our home?",
    "What is something about our love that feels timeless?",
    "How has your trust in love grown since being with me?",
    "What is a moment we shared where time seemed to stop?",
    "When do you feel the most tender toward me?",
    "What is a way I support your dreams that you appreciate?",
    "How can we make each other feel loved when we are apart?",
    "What is a gesture of mine that feels like a love letter without words?",
    "When did you first feel like we were building something lasting?",
    "What is a way our love has taught you about your own worth?",
    "How do you want us to keep curiosity alive between us?",
    "What is a memory of us in nature that stays with you?",
    "When have you felt most loved simply for existing?",
    "What is a way I show love that is uniquely mine?",
    "How has being my partner made you a better friend to others?",
    "What is a moment of vulnerability from me you hold close?",
    "When do you feel the fullest kind of happy with me?",
    "What is a way we have learned to soften toward each other?",
    "How do you want to be comforted during seasons of grief?",
    "What is a simple pleasure we share that feels sacred?",
    "When have you felt the most tenderly protected by me?",
    "What is a way I remind you of your goodness when you forget?",
    "How do you want us to keep falling in love with the everyday?",
    "What is a memory where our quiet said more than words could?",
    "When do you feel most grateful for the life we share?",
    "What is a way our love has made you more patient with yourself?",
    "How has being loved by me reshaped what you want in life?",
    "What is a trait of mine you hope our future echoes?",
    "When have you felt most deeply at home in my arms?",
    "What is a way I bring out a version of you that you love?",
    "How do you want us to honor the love we have five, ten, twenty years on?",
    "What is a moment between us that you wish you could live inside forever?"
  ]
};
